### ISSUE TITLE
"Time to end" entity

### ISSUE THREAD

**Issue by SmilinStanSStanman** [albaintor/homeassistant_electrolux_status#2]
Time to end entity shows time in seconds instead of in minutes with my dishwasher.
It is happening the same problem with "Start time" entity.

Thanks for your work!

**Comment by caveman85** [comment]
I've updated the instance in Home Assistance, but still no data, error 504?

`504, message='Gateway Timeout', url=URL('https://api.eu.ocp.electrolux.one/appliance/api/v2/appliances/914550541_00:15100011-443E072CA62D/capabilities')
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 118, in setup_entities
    appliance_capabilities = await self.api.get_appliance_capabilities(appliance.get('applianceId'))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 141, in get_appliance_capabilities
    result = await self._api_client.get_appliance_capabilities(base_url, token, id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/apiClient.py", line 182, in get_appliance_capabilities
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.eu.ocp.electrolux.one/appliance/api/v2/appliances/914550541_00:15100011-443E072CA62D/capabilities')
`
Any support please?

**Comment by albaintor** [comment]
Fixed in the next release
