### ISSUE TITLE
Platform electrolux_status does not generate unique IDs.

### ISSUE THREAD

**Issue by kovacsla** [albaintor/homeassistant_electrolux_status#23]
HACS version: 1.34.0
HA Core: 2024.2.1
Supervisor: 2024.01.1
Operating System: 11.5

I deleted integration and recreate it last version (1.08) 
I got the error message below:

```
2024-02-10 19:46:37.024 ERROR (MainThread) [homeassistant.components.sensor] Platform electrolux_status does not generate unique IDs. ID 8d17c1bff0cdf929c2c4eea68b8374cd-applianceMode--914600334_01:20800485-443E072B410B is already used by sensor.electrolux_moso_masa_appliancemode - ignoring sensor.ELECTROLUX_Mosó Masa__applianceMode
2024-02-10 19:46:37.052 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform electrolux_status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 684, in _async_add_entity
    entry = entity_registry.async_get_or_create(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 719, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
2024-02-10 19:46:37.057 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform electrolux_status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 684, in _async_add_entity
    entry = entity_registry.async_get_or_create(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 719, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
2024-02-10 19:46:37.061 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up electrolux_status platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 684, in _async_add_entity
    entry = entity_registry.async_get_or_create(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 719, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
2024-02-10 19:46:37.066 ERROR (MainThread) [homeassistant.components.number] Error while setting up electrolux_status platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 684, in _async_add_entity
    entry = entity_registry.async_get_or_create(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 719, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by cedsp** [comment]
I have the sabe problem

**Comment by albaintor** [comment]
I have found the problem. Fixed in the next release (but I am unable to test it so please confirm this is fixed)

**Comment by kovacsla** [comment]
I updated the integration but the error is still there.

**Comment by albaintor** [comment]
Can you dump your appliance data (capabilities + state)  please from the standalone script (unless you did it in another post so then give me the link again) THanks

**Comment by kovacsla** [comment]
[laci.txt](https://github.com/albaintor/homeassistant_electrolux_status/files/14231912/laci.txt)

**Comment by allistermaguire** [comment]
I also have a similar issue, but mine doesn't cause any impact. Not sure if it helps.
```
2024-02-12 08:33:48.858 ERROR (MainThread) [homeassistant.components.sensor] Platform electrolux_status does not generate unique IDs. ID 4fcdd401496437c964d4afe3f0dc940e-applianceMode--914900934_02:21113025-443E0727F18E is already used by sensor.electrolux_washer_appliancemode - ignoring sensor.ELECTROLUX_Washer__applianceMode
2024-02-12 08:33:48.876 ERROR (MainThread) [homeassistant.components.sensor] Platform electrolux_status does not generate unique IDs. ID 4fcdd401496437c964d4afe3f0dc940e-applianceMode--916099091_01:22901331-443E07376EA3 is already used by sensor.electrolux_dryer_appliancemode - ignoring sensor.ELECTROLUX_Dryer__applianceMode
```

**Comment by albaintor** [comment]
This should be fixed in the next release

**Comment by kovacsla** [comment]
I updated the integration (1.0.10) and error is fixed. Thx
