### ISSUE TITLE
Failed to configure

### ISSUE THREAD

**Issue by cedsp** [albaintor/homeassistant_electrolux_status#28]
Core
2024.2.1
Supervisor
2024.01.1
Operating System
Front-end
20240207.1
[error_log-4.txt](https://github.com/albaintor/homeassistant_electrolux_status/files/14238706/error_log-4.txt)

When configuring, I get the failed to configure message.

Este erro originou-se de uma integração personalizada.

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/__init__.py:100
Integration: Electrolux Care Integration V2 (documentation, issues)
First occurred: 09:54:11 (5 occurrences)
Last logged: 10:04:34

Could not log in to ElectroluxStatus, Expecting value: line 1 column 1 (char 0)

**Comment by albaintor** [comment]
This error means that your credentials are not valid. Did you use the same login/password as in the app ?

**Comment by cedsp** [comment]
Yes. I use the same credentials as the electrolux home+ app.
is the app we use here at LAT.

**Comment by cedsp** [comment]
The App requests a strong password, with capital letters, numbers and special characters.
could this be a problem?

**Comment by albaintor** [comment]
No it shouldn't be an issue. Please post the homeassistant.log file

**Comment by cedsp** [comment]
[home-assistant.zip](https://github.com/albaintor/homeassistant_electrolux_status/files/14273653/home-assistant.zip)

**Comment by albaintor** [comment]
From the logs the error comes from the library wrapper, I will forward this error to the creator of the library
``` 
 File "/config/custom_components/electrolux_status/__init__.py", line 94, in async_login
    token = await self.api.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/electroluxwrapper/oneAppApi.py", line 101, in get_user_token
    id_token = await gigya_client.login_user(self._username, self._password)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/electroluxwrapper/gigyaClient.py", line 210, in login_user
    ids = await self.get_ids()
          ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/electroluxwrapper/gigyaClient.py", line 147, in get_ids
    data: SocializeGetIdsResponse = await response.json(content_type=None)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1182, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by albaintor** [comment]
I have raised an issue on his side :
https://github.com/Woyken/py-electrolux-ocp/issues/7

**Comment by albaintor** [comment]
Hi it should be fixed in the v1.0.12

**Comment by cedsp** [comment]
The problem was solved.
thanks

**Comment by slingshot74** [comment]
Just installed the new version, works again. Thanks!

**Comment by OsiMood** [comment]
Same issue here with the latest version:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 48, in async_setup_entry
    if not await coordinator.async_login():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 110, in async_login
    raise ex
  File "/config/custom_components/electrolux_status/__init__.py", line 103, in async_login
    token = await self.api.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 111, in get_user_token
    token = await self._api_client.exchange_login_user(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApiClient.py", line 136, in exchange_login_user
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://api.eu.ocp.electrolux.one/one-account-authorization/api/v1/token')`

**Comment by OsiMood** [comment]
Same issue here with latest version
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 48, in async_setup_entry
    if not await coordinator.async_login():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 110, in async_login
    raise ex
  File "/config/custom_components/electrolux_status/__init__.py", line 103, in async_login
    token = await self.api.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 111, in get_user_token
    token = await self._api_client.exchange_login_user(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApiClient.py", line 136, in exchange_login_user
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://api.eu.ocp.electrolux.one/one-account-authorization/api/v1/token')`
