### ISSUE TITLE
{"message":"Missing Authentication Token"}

### ISSUE THREAD

**Issue by kovacsla** [albaintor/homeassistant_electrolux_status#34]
I restarted the HA, and get the error message:

```
2024-02-19 10:50:59.468 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *************@gmail.com for electrolux_status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 48, in async_setup_entry
    if not await coordinator.async_login():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 110, in async_login
    raise ex
  File "/config/custom_components/electrolux_status/__init__.py", line 103, in async_login
    token = await self.api.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 111, in get_user_token
    token = await self._api_client.exchange_login_user(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApiClient.py", line 136, in exchange_login_user
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://api.eu.ocp.electrolux.one/one-account-authorization/api/v1/token')
```

**Comment by kovacsla** [comment]
It has been fixed, it seems that the error was on Electrolux's side. Has anyone else experienced this?

**Comment by kovacsla** [comment]
The error has disappeared, the error was probably on the Electrolux side.
