### ISSUE TITLE
Error Setting up entry

### ISSUE THREAD

**Issue by sultanhq** [albaintor/homeassistant_electrolux_status#4]
Getting this error after installing the library:

I have an AEG Dishwasher, which I have renamed from the default 'Dishwasher' to 'AEG Dishwasher' (assuming this was what was meant in the docs by setting an alias 🤷 )

Error setting up entry r$$$$$$$$$s@gmail.com for electrolux_status
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 133, in setup_entities
    app.setup(ElectroluxLibraryEntity(name=appliance_name, status=connection_state, state=appliance_status,
  File "/config/custom_components/electrolux_status/api.py", line 393, in setup
    ElectroluxSensor(
  File "/config/custom_components/electrolux_status/entity.py", line 35, in __init__
    self.entity_id = ENTITY_ID_FORMAT.format(f"{self.get_appliance.brand}_{self.get_appliance.name}_{self.entity_source}_{self.entity_attr}")
                                                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'brand'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 57, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/__init__.py", line 140, in setup_entities
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

**Comment by slingshot74** [comment]
@sultanhq This is an know error and @albaintor will fix it later

**Comment by sultanhq** [comment]
Thanks,
