### ISSUE TITLE
Electrolux Fridge Not Supported

### ISSUE THREAD

**Issue by cloudbr34k84** [albaintor/homeassistant_electrolux_status#49]
Hey just saw that there is a forked version of the previous Electrolux App.

Im located in Australia so using Electrolux Life (APAC region)

My fridge is not showing, how can i help? 

below is the logs info im seeing
```
This error originated from a custom integration.

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/coordinator.py:38
integration: Electrolux Care Integration V2 (documentation, issues)
First occurred: 12:19:32 pm (3 occurrences)
Last logged: 12:22:37 pm

Could not log in to ElectroluxStatus, 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.ocp.electrolux.one/one-account-user/api/v1/identity-providers?brand=electrolux&email=cloudbr34k84@gmail.com')
```
```
Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 12:19:32 pm (3 occurrences)
Last logged: 12:22:37 pm

Error setting up entry cloudbr34k84@gmail.com for electrolux_status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 46, in async_setup_entry
    if not await coordinator.async_login():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/coordinator.py", line 39, in async_login
    raise ex
  File "/config/custom_components/electrolux_status/coordinator.py", line 32, in async_login
    token = await self.api.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 125, in get_user_token
    gigya_client = await self._get_gigya_client()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 390, in _get_gigya_client
    data = await self._get_identity_providers()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 354, in _get_identity_providers
    providers = await self._api_client.get_identity_providers(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApiClient.py", line 195, in get_identity_providers
    response_json = await response.json()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.ocp.electrolux.one/one-account-user/api/v1/identity-providers?brand=electrolux&email=cloudbr34k84@gmail.com')
```
```
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 12:15:52 pm (3 occurrences)
Last logged: 12:15:58 pm

Unable to install package pycountry==22.3.5: ERROR: Cannot install pycountry==22.3.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by kingy444** [comment]
what fridge model do you have ? I would suggest fixing those conflicts up first of all so you can get the json from the api

**Comment by cloudbr34k84** [comment]
Fridge has been added
EHE6899SA
by ELECTROLUX
