### ISSUE TITLE
No devices

### ISSUE THREAD

**Issue by nesheimt** [albaintor/homeassistant_electrolux_status#55]
I have a Electrolux washer and a Electrolux dryer but the integration reports that there are "no devices or entities":
![image](https://github.com/user-attachments/assets/c47437a5-5661-48fe-9e1a-7b3fb7134ecd)

Washer model: EW8F8669Q9
Dryer model: EW9H869E9

I see that the dryer is in the "supported list" but the washer is not. I have enabled debug logging, and have been looking for the log, but must admit I cannot find it, yet.

**Comment by fjosepose** [comment]
Log:
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 11:25:20 PM (1 occurrences)
Last logged: 11:25:20 PM

Error setting up entry torbjorn.nesheim@mac.com for electrolux_status
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 46, in async_setup_entry
    if not await coordinator.async_login():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/coordinator.py", line 39, in async_login
    raise ex
  File "/config/custom_components/electrolux_status/coordinator.py", line 32, in async_login
    token = await self.api.get_user_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 128, in get_user_token
    token = await self._api_client.exchange_login_user(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApiClient.py", line 142, in exchange_login_user
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://api.eu.ocp.electrolux.one/one-account-authorization/api/v1/token')

**Comment by fjosepose** [comment]
This error originated from a custom integration.

Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/coordinator.py:38
integration: Electrolux Care Integration V2 (documentation, issues)
First occurred: 11:25:20 PM (1 occurrences)
Last logged: 11:25:20 PM

Could not log in to ElectroluxStatus, 429, message='', url=URL('https://api.eu.ocp.electrolux.one/one-account-authorization/api/v1/token')
