### ISSUE TITLE
Errors while setting up for KSK998230T Oven - capabilities

### ISSUE THREAD

**Issue by Imperial-Guard** [albaintor/homeassistant_electrolux_status#7]
First of all thanks for your effort in this addon. 

While setting up I got the error message below and it seems to be that I missing all temperature entities not sure if this is related to underneath error:

`429, message='', url=URL('https://api.eu.ocp.electrolux.one/appliance/api/v2/appliances/944066778_02:23506765-443E0739F542/capabilities')
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 119, in setup_entities
    appliance_capabilities = await self.api.get_appliance_capabilities(appliance_id)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/oneAppApi.py", line 141, in get_appliance_capabilities
    result = await self._api_client.get_appliance_capabilities(base_url, token, id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyelectroluxocp/apiClient.py", line 182, in get_appliance_capabilities
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='', url=URL('https://api.eu.ocp.electrolux.one/appliance/api/v2/appliances/944066778_02:23506765-443E0739F542/capabilities'`

**Comment by albaintor** [comment]
Hi are you sure you have the last version (beta 2 release) ?
The lines quoted don't correspond to the beta2 version

**Comment by albaintor** [comment]
Please update to the last beta https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0-beta4 from HACS (refresh integration)

**Comment by albaintor** [comment]
Please update to the last beta https://github.com/albaintor/homeassistant_electrolux_status/releases/tag/v1.0-beta4 from HACS (refresh integration)

**Comment by slingshot74** [comment]
In the beta4 version the appliancemode doesn't exist anymore. I used that sensor to determine if the dryer was on or off. 
Does anyone know which other sensor to pick best?
