### ISSUE TITLE
aiohttp gets 404, message='Not Found'

### ISSUE THREAD

**Issue by rusteff** [albaintor/homeassistant_electrolux_status#76]
#After uppgrading to the new version the integration stopped working.
I have tried deleting the integration and adding it again.
This is the error i am getting.

Error setting up entry [XXXX@gmail.com](mailto:XXXX@gmail.com) for electrolux_status
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/coordinator.py", line 366, in setup_entities
    appliance_capabilities = await self.api.get_appliance_capabilities(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApi.py", line 177, in get_appliance_capabilities
    result = await self._api_client.get_appliance_capabilities(base_url, token, id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyelectroluxocp/oneAppApiClient.py", line 305, in get_appliance_capabilities
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://api.eu.ocp.electrolux.one/appliance/api/v2/appliances/900277470033005641100106/capabilities'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/coordinator.py", line 374, in setup_entities
    raise ConfigEntryNotReady(
homeassistant.exceptions.ConfigEntryNotReady: Electrolux unable to retrieve capabilities. Cancelling setup

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 71, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/coordinator.py", line 404, in setup_entities
    raise UpdateFailed from exception
homeassistant.helpers.update_coordinator.UpdateFailed

**Comment by albaintor** [comment]
This is really strange, this part (the electrolux library) has not changed. Are you able to see the appliance from the electrolux app with the same credentials ?

**Comment by rusteff** [comment]
Yes in the app I can se all my appliances. I tried charging password but same problem. When I revert back to v1.0.19 it works again

**Comment by albaintor** [comment]
Ok this is a good hint. I'll dig into this

**Comment by albaintor** [comment]
Ok I have found why : on your appliance the API won't report its capabilities (don't know why), which is necessary to build the entities. But in the former version I ignored that and build entities on reported data. Less precise but still working. I will revert this

**Comment by albaintor** [comment]
This will be fixed in the next release v2.0.4

**Comment by albaintor** [comment]
Should be fixed in https://github.com/albaintor/homeassistant_electrolux_status/tree/v2.0.5

**Comment by kingy444** [comment]
Commented over on the other issue too - but I don't think we should be ignoring these errors, the setup is failing because the device is unhealthy 

If the api is not returning good data then I expect no entities to be setup
