### ISSUE TITLE
TypeError on setting up

### ISSUE THREAD

**Issue by tieskuh** [albaintor/homeassistant_electrolux_status#8]
Hi Albaintor,

Thank you very much for continuing development on this integration!
I tried setting up the new release but got an error after entering my credentials. So setting up the integration works, but no entities are being loaded.

I have two AEG machines which worked correctly in the previous integration.

- AEG Lavamat 9000 - L9FEN96BC
- AEG Lavatherm 9000 - T9DEN98BC

Both machines have a name in the AEG app.

```
Error setting up entry e@mail.com for electrolux_status
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 142, in setup_entities
    appliance.setup(ElectroluxLibraryEntity(name=appliance_name, status=connection_status,
  File "/config/custom_components/electrolux_status/api.py", line 274, in setup
    for capability in capabilities_names:
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 59, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/__init__.py", line 149, in setup_entities
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed
```

I downloaded the integration via HACS by adding your GIT repository as custom repository.

The strange thing is, it downloaded this version. Which does not correspond to any of your releases.

![image](https://github.com/albaintor/homeassistant_electrolux_status/assets/115901851/6216a6d7-4563-4e3f-b259-003e12b2a50b)

**Comment by tieskuh** [comment]
Latest version you just published, still same error.

```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 14:33:49 (2 occurrences)
Last logged: 14:34:26

Error setting up entry e@mail.com for electrolux_status
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 142, in setup_entities
    appliance.setup(ElectroluxLibraryEntity(name=appliance_name, status=connection_status,
  File "/config/custom_components/electrolux_status/api.py", line 147, in setup
    for capability in capabilities_names:
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 59, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/__init__.py", line 149, in setup_entities
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed
```

**Comment by slingshot74** [comment]
I have that same error now

**Comment by tieskuh** [comment]
Issue is solved in beta 5!
Thank you!!

**Comment by slingshot74** [comment]
I can confirm it's solved. Awesome!
