### ISSUE TITLE
Issue with new version “Invalid Config”

### ISSUE THREAD

**Issue by Teone55** [albaintor/homeassistant_electrolux_status#80]
I have an issue with the last version. Here the log:

Registratore: homeassistant.setup
Fonte: setup.py:334
Prima occorrenza: 02:23:15 (1 occorrenze)
Ultima registrazione: 02:23:15

Setup failed for custom integration 'electrolux_status': Unable to import component: cannot import name 'OneAppApi' from 'pyelectroluxocp' (/usr/local/lib/python3.12/site-packages/pyelectroluxocp/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/electrolux_status/__init__.py", line 25, in <module>
    from .coordinator import ElectroluxCoordinator
  File "/config/custom_components/electrolux_status/coordinator.py", line 11, in <module>
    from pyelectroluxocp import OneAppApi
ImportError: cannot import name 'OneAppApi' from 'pyelectroluxocp' (/usr/local/lib/python3.12/site-packages/pyelectroluxocp/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/electrolux_status/__init__.py", line 25, in <module>
    from .coordinator import ElectroluxCoordinator
  File "/config/custom_components/electrolux_status/coordinator.py", line 11, in <module>
    from pyelectroluxocp import OneAppApi
ImportError: cannot import name 'OneAppApi' from 'pyelectroluxocp' (/usr/local/lib/python3.12/site-packages/pyelectroluxocp/__init__.py)

**Comment by albaintor** [comment]
This is strange : the pyelectroluxocp library used by the component seems to be not correctly installed.
What kind of setup do you have ? 
`ImportError: cannot import name 'OneAppApi' from 'pyelectroluxocp' (/usr/local/lib/python3.12/site-packages/pyelectroluxocp/init.py)`

I don't think this is possible to get the content of this file /usr/local/lib/python3.12/site-packages/pyelectroluxocp/init.py (on host machine of the VM). But clearly something is wrong in the setup. The manifest.json file tells homeassistant which dependencies to install. You can try to download manually `pyelectroluxocp` library and paste the `pyelectroluxocp` folder into `custom_components/electrolux_status`

**Comment by Teone55** [comment]
Downgraded to version 1.0.19 and perfectly working. This is strange. If you want I’m available to make some tests.

I have a raspberry with HA installed, that’s it. And your integration installed with HACS, with no change in settings. All standard.

**Comment by albaintor** [comment]
The difference is the dependency library that has been upgraded to 0.0.19 in the meantime and which is targeted by the manifest file of the integration. This should not happen and I don't understand why : it is as if the setup would grab the previous version of the dependency.
I have posted a ticket to Woyken https://github.com/Woyken/py-electrolux-ocp/issues/13 to investigate. I am sure this is an easy fix but where....
