### ISSUE TITLE
New Version 2.0.6 Failed to set up

### ISSUE THREAD

**Issue by bdb12** [albaintor/homeassistant_electrolux_status#94]
So I updated the integration by removing the old one completely, restarting HA and reinstalling. Now it doen't work at all! I get failed to set up. Does this below help from HA logs?

Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/coordinator.py", line 402, in setup_entities
    appliance.setup(
  File "/config/custom_components/electrolux_status/api.py", line 618, in setup
    if (entity := self.get_entity(static_attribute)) is None:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/api.py", line 577, in get_entity
    return electrolux_entity_factory(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Appliance.get_entity.<locals>.electrolux_entity_factory() got an unexpected keyword argument 'entity_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/electrolux_status/__init__.py", line 71, in async_setup_entry
    await coordinator.setup_entities()
  File "/config/custom_components/electrolux_status/coordinator.py", line 413, in setup_entities
    raise UpdateFailed from exception
homeassistant.helpers.update_coordinator.UpdateFailed

**Comment by wgumaa** [comment]
Same here!

**Comment by kingy444** [comment]
the order of the two PR's being merged wiped out some required code - fixing up a PR now
